Added support for identifier prefix for older ESX versions.
project-error/npwd pull request #244
Opened 2021-05-23 05:03 UTC by iTexZoz

2021-05-23 05:12 UTC, RockySouthpaw commented
> > This is useful for other than people using older esx as there's variations of esx and peoples frameworks that don't do the whole string split. :)
> 
> I found the project interesting, I'm considering it to replace the gcphone on my server, however, having a very old version of ESX that has been modified all over the place by anyone, I thought this change would be useful for people other than me.

Thank you for the PR :). I myself don't split the string and normally just manually create a row in my db when i test the phone 😂 (since branch changing + modifing the code everytime isn't worth it.)

 I'll request code review from others, but this looks okay to me aside from `"useIdentifierPrefix"` being false by default since the current default is true.

2021-05-23 14:52 UTC, itschip commented on config.json
> +  "useIdentifierPrefix": false,
This should go under database.

2021-05-27 04:06 UTC, RockySouthpaw commented
@iTexZoz Can you apply the requested change so this can be merged?

2021-05-30 21:22 UTC, RockySouthpaw requested changes

2021-06-08 18:51 UTC, itschip commented
@iTexZoz Are you able to resolve the current issue?

2021-06-09 11:57 UTC, iTexZoz commented on config.json
> +  "useIdentifierPrefix": false,
Ho, sorry

2021-06-09 11:58 UTC, iTexZoz commented
@itschip Sorry for the delay in answering, it's done!

2021-06-09 17:05 UTC, TasoOneAsia approved these changes

2021-06-09 17:08 UTC, merged