feat(client/photo): add the ability to use a custom image server
project-error/npwd pull request #256
Opened 2021-07-01 23:45 UTC by AvarianKnight

2021-07-02 01:04 UTC, RockySouthpaw commented
Can you update the read me with this PR?

2021-07-02 06:09 UTC, TasoOneAsia approved these changes
Looks fine for now aside from not cleaning up in some bad areas. But will worry about that later.

2021-07-02 06:13 UTC, TasoOneAsia commented
@RockySouthpaw docs are not yet public, so nothing relevant to change yet. Ill probably public them tomorrow.

2021-07-08 05:21 UTC, TasoOneAsia requested changes
Few things I missed first time around

2021-07-08 05:21 UTC, TasoOneAsia commented on resources/client/cl_photo.ts
>          authorization: `Client-ID ${SCREENSHOT_BASIC_TOKEN}`,
With the change to add custom image servers, there may be points where an authorization header isn't required. We should handle for that.

2021-07-08 05:21 UTC, TasoOneAsia commented on resources/client/cl_photo.ts
> +         imageLink = `${config.images.url.includes('https') ? 'https' : 'http'}://${JSON.parse(data).files[0].url}`;
This can be a variable resp format.

2021-07-14 18:25 UTC, itschip commented
@AvarianKnight Are you able to take a look at the comments from Taso?

2021-07-15 15:52 UTC, itschip commented
@AvarianKnight Please switch branch to 'develop', not 'master'

2021-10-04 18:40 UTC, TasoOneAsia commented
Revamped by #321

2021-10-04 18:40 UTC, closed without merging