Offline Player Handling
project-error/npwd pull request #257
Opened 2021-07-02 03:39 UTC by AvarianKnight

This is a pull request to add offline player handling, this isn't done and should be considered a draft.

2021-07-02 04:15 UTC, RockySouthpaw commented
Tag me when this changes so I can remove the label :)

2021-07-08 05:24 UTC, TasoOneAsia requested changes

2021-07-08 05:24 UTC, TasoOneAsia commented on resources/server/players/player.service.ts
> -    if (!player)
Just return null if the player isn't found.

2021-09-25 13:11 UTC, AvarianKnight commented
Closing this as this likely won't be needed with the new messaging refactor.

2021-09-25 13:11 UTC, closed without merging