Refactor/twitter
project-error/npwd pull request #338
Opened 2021-11-16 13:02 UTC by itschip

2021-11-17 19:37 UTC, TasoOneAsia commented
Considering high LOC count, will see if I can squeeze this is for review this weekend.

2021-11-17 19:39 UTC, itschip commented
> Considering high LOC count, will see if I can squeeze this is for review this weekend.

Either way, I think its more important to test it. I'll send some files that should be looked at.

2021-11-21 22:17 UTC, TasoOneAsia requested changes
Just a couple things to look over

2021-11-21 22:17 UTC, TasoOneAsia commented on resources/server/twitter/twitter.controller.ts
> +onNetPromise(TwitterEvents.GET_OR_CREATE_PROFILE, async (reqObj, resp) => {
Missing types passed to generic, possibly creating some type safety concerns.

2021-11-21 22:17 UTC, TasoOneAsia commented on resources/server/twitter/twitter.controller.ts
> +    console.log('getting some filtered tweets');
```suggestion
```

2021-11-21 22:17 UTC, TasoOneAsia commented on resources/server/twitter/twitter.db.ts
> +    console.log(profile);
```suggestion
```

2021-11-21 22:17 UTC, TasoOneAsia commented on resources/server/twitter/twitter.service.ts
> +        console.log(defaultProfileNames);
In regards to all the console logs everywhere, I don't mind implementing some further logging using our winston logger system. 

```suggestion
```

2021-11-21 22:17 UTC, TasoOneAsia commented on resources/server/twitter/twitter.db.ts
> +        ORDER BY npwd_twitter_tweets.id DESC LIMIT 50
As requested.

```suggestion
        ORDER BY npwd_twitter_tweets.id DESC LIMIT 25
```

2021-11-21 22:17 UTC, TasoOneAsia commented on resources/server/twitter/twitter.service.ts
> +    const identifier = PlayerService.getIdentifier(reqObj.source);
This can potentially return null if for some reason our source isn't present in the PlayerService maps. *Might* be worth sanity checking but meh.

2021-11-21 22:17 UTC, TasoOneAsia commented on resources/server/twitter/twitter.service.ts
> +      resp({ status: 'ok' });
> // should we get the profile here?
 
I agree with this comment wholeheartedly. Its pretty typical for an API to return final data after a mutation operation.

2021-11-21 22:17 UTC, TasoOneAsia commented on phone/src/apps/twitter/hooks/useTwitterService.ts
> +  //const [profile] = useRecoilValue(waitForAll([twitterState.profile]))
If we don't need to keep this around let's get rid of.

2021-11-21 22:17 UTC, TasoOneAsia commented on phone/src/apps/twitter/hooks/useTwitterNotifications.ts
> +  //const [profile] = useRecoilValue(waitForAll([twitterState.profile]))
```suggestion
```

2021-11-21 22:17 UTC, TasoOneAsia commented on phone/src/apps/twitter/components/buttons/ReportButton.tsx
> +      }, LOADING_TIME);
This seems a little bit odd as we are literally setting the loading state after we resolve the promise from the server. Also, this was utilized mostly for the previous fake loading system.

2021-11-21 22:17 UTC, TasoOneAsia commented on phone/src/apps/twitter/components/buttons/LikeButton.tsx
> +        setLoading(false);
This seems a little bit odd as we are literally setting the loading state after we resolve the promise from the server. Also, this was utilized mostly for the previous fake loading system.

2021-11-21 22:17 UTC, TasoOneAsia commented on phone/src/apps/twitter/components/AddTweetModal.tsx
> +
Be mindful that spamming enter here would result in multiple promise events being fired, if the previous promise isn't yet resolved.

2021-11-21 22:17 UTC, TasoOneAsia commented on phone/src/apps/match/components/profile/ProfileForm.tsx
> +  if (!profile && !ResourceConfig.match.allowEditableProfileName) {
nice match bro

2021-11-22 00:50 UTC, RockySouthpaw commented
Not related to current pr but may need to be addressed on this refactor:

**Bug**: search icon overlaps profile when search is selected
![image](https://user-images.githubusercontent.com/55056068/142786197-fcf98fd1-e58a-407d-b8aa-94aa86919b3f.png)

2021-11-22 02:07 UTC, RockySouthpaw commented
**?????: Some twitter error but didnt do anything**
![image](https://user-images.githubusercontent.com/55056068/142789173-6dbb193d-6fd8-45cc-997c-57f6c357c5a1.png)


**Bug 1: New Line Restriction Issue**
If you are at `10`( the limit) the warning message appears. However, if you exceed that line by just 1, you can send an unlimited amount of new lines. Resulting in [this](https://user-images.githubusercontent.com/55056068/142787695-2746a55b-6b22-46c5-9888-4a95333256de.png)

**Bug 2: Cant create twitter profiles if the name is the same**
![image](https://user-images.githubusercontent.com/55056068/142789671-8c2da907-44fd-4a08-95d8-28b5bc66f42c.png)
Identifier isn't the same as whats being added ether so not sure the case here.

**Performance issue: Loading emojis**
It's slow as shit kek. Idk if this can be improved but using emojis is like a 5 second load wait **everytime you close and open twitter**. Its fine if you dont exit it as it stays loaded but yea, slow.

 **Tested Following:**
  - Sending Tweets ⚠️(Mostly✔️ though)
  - Sending Emoji ⚠️(Mostly✔️ though)
  - Fetching Tweets ✔️ (Updates in real time now)
  - Reporting Tweets ✔️ (Didn't test the webhook though, but the log regarding it not being set is correct.)
  - Tagging ✔️(Receive notifications when phone is closed + open. Made sure to not open phone first too)
  - Duplicate Name Profiles ❌
  
  Didnt test anything to do with bio stuff yet

2021-11-22 20:36 UTC, itschip commented
> Bug 2: Cant create twitter profiles if the name is the same

@RockySouthpaw The "issue" with duplicate names, is intended. We simply don't allow profiles to share the same name.

2021-11-22 20:42 UTC, RockySouthpaw commented
> > Bug 2: Cant create twitter profiles if the name is the same
> 
> @RockySouthpaw The "issue" with duplicate names, is intended. We simply don't allow profiles to share the same name.

I see, may want to test it some more then because I was getting some weird results when testing where one client was having issues loading when this was encountered. Both actually got the prompt to create a profile on twitter.

Though wouldn’t it be more simple if everyone has to register a profile? Or is that too many queries? Not sure if we have a reference map of current twitter usernames we compare to when registering new users or if it would require fetch scalar for every person who registers kek.

2021-11-22 20:49 UTC, TasoOneAsia commented
> Edit: I don’t recall ever seeing a UI warning so will need to test again

There isn't one at the moment, but the server should respond with a specified error code on the fetch request

2021-11-23 06:06 UTC, TasoOneAsia requested changes

2021-11-23 06:06 UTC, TasoOneAsia commented on phone/src/apps/twitter/components/profile/ProfilePrompt.tsx
> +    fetchNui<ServerPromiseResp<any>>(eventName, { ...profile, profile_name: profileName }).then(
Replace the generic type in response with something other than `any`.

2021-11-23 08:12 UTC, RockySouthpaw commented
> Not related to current pr but may need to be addressed on this refactor:
> 
> **Bug**: search icon overlaps profile when search is selected ![image](https://user-images.githubusercontent.com/55056068/142786197-fcf98fd1-e58a-407d-b8aa-94aa86919b3f.png)

Created an issue for this https://github.com/project-error/npwd/issues/369

2021-11-28 04:26 UTC, RockySouthpaw commented
> > Not related to current pr but may need to be addressed on this refactor:
> > **Bug**: search icon overlaps profile when search is selected ![image](https://user-images.githubusercontent.com/55056068/142786197-fcf98fd1-e58a-407d-b8aa-94aa86919b3f.png)
> 
> Created an issue for this #369

confirmed resolved

2021-11-28 04:32 UTC, RockySouthpaw commented
**"Bug"**
Missing translation for twitter_edit_profile_success

Just a minor fix.

**Bug: Off centered loading circle**
Only encountered when there are no tweets. 
![image](https://user-images.githubusercontent.com/55056068/143729703-5f86438d-9375-4b7d-853a-0d78c1b84267.png)

2021-11-28 04:33 UTC, RockySouthpaw commented
**Bug: New Line Restriction Issue**
If you are at `10`( the limit) the warning message appears. However, if you exceed that line by just 1, you can send an unlimited amount of new lines. Resulting in [this](https://user-images.githubusercontent.com/55056068/142787695-2746a55b-6b22-46c5-9888-4a95333256de.png)

This is still an issue

2021-11-28 19:14 UTC, TasoOneAsia commented
> @TasoOneAsia Emoji's load much better now though.

😄

2021-12-01 00:12 UTC, merged