Update vehicle anims for motorcycle
project-error/npwd pull request #758
Opened 2022-05-16 10:42 UTC by Deniel00

**Pull Request Description**

Updated in vehicle anims for working motorcycles.
![kép](https://user-images.githubusercontent.com/12788940/168575769-9799e818-8ddb-4bc3-a8bf-8a82206e1225.png)
_old anim_
![kép](https://user-images.githubusercontent.com/12788940/168575874-8ee1d7d8-0db2-46a4-a34d-ddaa1be33d15.png)

**Pull Request Checklist**:
* [x] Have you followed the guidelines in our Contributing document and Code of Conduct?
* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/project-error/npwd/pulls) for the same update/change?
* [x] Have you built and tested NPWD in-game after the relevant change?

2022-05-16 18:18 UTC, Mojito-Fivem commented
![image](https://user-images.githubusercontent.com/66041893/168656957-d13de28b-3dea-49fc-8c1a-ae00d5a695e1.png)
With your changes the ped now sits forward in the car and they have to leave the car, pull the phone out and put it away again to return to the normal driving animation. The same issue occurs on motorcycles where the pen is stuck with their hand in the air.

2022-05-17 02:45 UTC, RockySouthpaw commented
You'd need to change the dict/anim based off the class the player is in.

https://github.com/project-error/npwd/blob/8bec2f254dc57f18f9964df60538df0db2446124/resources/client/animations/animation.service.ts#L50

```ts
private handleCallAnimation(playerPed: number) {
    if (IsPedInAnyVehicle(playerPed, true)) {
      this.handleOnCallInVehicle(playerPed);
    } else {
      this.handleOnCallNormal(playerPed);
    }
  }

  private handleOpenAnimation(playerPed: number) {
    if (IsPedInAnyVehicle(playerPed, true)) {
      this.handleOpenVehicleAnim(playerPed);
    } else {
      this.handleOpenNormalAnim(playerPed);
    }
  }

  private handleCallEndAnimation(playerPed: number) {
    if (IsPedInAnyVehicle(playerPed, true)) {
      this.handleCallEndVehicleAnim(playerPed);
    } else {
      this.handleCallEndNormalAnim(playerPed);
    }
  }

  private handleCloseAnimation(playerPed: number) {
    if (IsPedInAnyVehicle(playerPed, true)) {
      this.handleCloseVehicleAnim(playerPed);
    } else {
      this.handleCloseNormalAnim(playerPed);
    }
  }
  ```
  You'd need to pass the class to the anim functions and then adjust the dics based off the class, can refer to the docs https://docs.fivem.net/natives/?_0x29439776AAA00A62. Your approach wouldn't work without rewriting your current pr entirely as you assume player vehicle = motorcycle where current method is just a blanket solution for most vehicle classes with the obvious exception of bikes. You'd just compare current class to see if its 8 and adjust the dics/anim locals accordingly.

2022-05-17 16:43 UTC, Deniel00 commented
As soon as possible I'm check this and editing.

2022-05-20 18:28 UTC, Deniel00 commented
I'm updated file for check player is in vehicle or motorcycles, but if in vehicles always restart opening animation and didn't find why made this.

2022-05-20 18:32 UTC, Mojito-Fivem requested changes

2022-05-20 18:32 UTC, Mojito-Fivem commented on resources/client/animations/animation.service.ts
> +    var DICT = 'anim@cellphone@in_car@ps';
Can you use let/const syntax

2022-05-20 18:32 UTC, Mojito-Fivem commented on resources/client/animations/animation.service.ts
> +		if (vehicleClass == 8){
formatting here

2022-05-20 18:32 UTC, Mojito-Fivem commented on resources/client/animations/animation.service.ts
> +    var DICT = 'anim@cellphone@in_car@ps';
use let/const

2022-05-20 18:32 UTC, Mojito-Fivem commented on resources/client/animations/animation.service.ts
> +		if (vehicleClass == 8){
formatting

2022-05-20 18:32 UTC, Mojito-Fivem commented on resources/client/animations/animation.service.ts
> +    var dict = 'anim@cellphone@in_car@ps';
Use let/const syntax

2022-05-20 18:37 UTC, Deniel00 commented
Fixed formating and using let/const

2022-06-02 08:41 UTC, itschip commented
I'll test it this week.

2022-07-04 15:28 UTC, Mojito-Fivem requested changes

2022-10-07 10:48 UTC, closed without merging